added !cocktail command
Kirbi-bot/Kirbi pull request #63
Opened 2017-07-29 20:12 UTC by naterchrdsn

resolves #54

2017-07-29 21:07 UTC, develogix requested changes
Need to fix indentation. If you have VS Code setup to use tabs over spaces, you can just press `alt+shift+f`.

2017-07-29 21:07 UTC, develogix commented on commands/cocktail.js
> +        let ingredients = Object.entries(result).slice(7,22).map(entry => entry[1]);
indentation... TABS vs. SPACES

2017-07-29 21:07 UTC, develogix commented on commands/cocktail.js
> +											if (ratios[index] !== '' && ratios[index] !== '\n') {
More indentation

2017-07-29 21:07 UTC, develogix commented on commands/cocktail.js
> +													ingredientsList += `* ${element}\n`;
More indentation

2017-07-29 21:07 UTC, develogix commented on commands/cocktail.js
> +									inline: true
More indentation

2017-07-29 21:07 UTC, develogix commented on commands/cocktail.js
> +									value: result.strInstructions,
More indentation

2017-07-29 21:07 UTC, develogix commented on commands/cocktail.js
> +									fields: fields
More indentation

2017-07-30 14:10 UTC, naterchrdsn commented
ready

2017-07-31 12:13 UTC, develogix approved these changes

2017-07-31 12:14 UTC, merged