Streamlining, resolves #79
Kirbi-bot/Kirbi pull request #82
Opened 2017-08-11 21:11 UTC by naterchrdsn

2017-08-11 21:34 UTC, Morandustries requested changes
Couple comments

2017-08-11 21:34 UTC, KnightVision90 commented on lib/commands.js
>  const Kirbi = require('../kirbi');
looks like this file has spaces instead of tabs

2017-08-11 21:34 UTC, KnightVision90 commented on lib/commands.js
> +                if (module) {
just add && module.commands and remove the extra nesting below

2017-08-11 21:34 UTC, KnightVision90 commented on lib/onEvent/message.js
> +		return msg.channel.send(output).then(message => msg.delete());
remove message from the then since its not used. replace with `()`

2017-08-12 01:28 UTC, naterchrdsn commented on lib/onEvent/message.js
> +		return msg.channel.send(output).then(message => msg.delete());
fixed

2017-08-12 01:28 UTC, naterchrdsn commented on lib/commands.js
> +                if (module) {
fixed

2017-08-12 14:30 UTC, Morandustries approved these changes

2017-08-12 14:30 UTC, merged